#!/bin/bash

export LD_LIBRARY_PATH="./lib":$LD_LIBRARY_PATH

export OMP_NUM_THREADS=5

FASTWIG_TABLES_PATH=./data_folder/fastwig_tables/

HASH_TABLES_STORE_PATH=./data_folder/hashed_21j/

DRAWS_STORE_PATH=./data_folder/collected_draws

DSPIN=3

LENGTH=30000

SIGMA=0.40

BURNIN=10

VERBOSITY=0

now=$(date)
echo
echo "Starting Metropolis-Hastings algorithm... [ NUM_OF_THREADS = ${OMP_NUM_THREADS} DSPIN = ${DSPIN} LENGTH = ${LENGTH} ]... (now: $now)"

bin/Metropolis_Hastings_parallel_run  $OMP_NUM_THREADS  $DSPIN  $LENGTH  $SIGMA  $BURNIN  $VERBOSITY  $DRAWS_STORE_PATH  $HASH_TABLES_STORE_PATH
            
now=$(date)
echo
echo "... completed! (now: $now)"

