#!/bin/bash

export LD_LIBRARY_PATH="./lib":$LD_LIBRARY_PATH

export OMP_NUM_THREADS=1

FASTWIG_TABLES_PATH=./data_folder/fastwig_tables/

HASH_TABLES_STORE_PATH=./data_folder/hashed_21j/

DRAWS_STORE_PATH=./data_folder/collected_draws

DSPIN=1

LENGTH=1000000

SIGMA=0.25

BURNIN=10

VERBOSITY=0

echo Running all tests... 

# bin/test_jsymbols $DATADIR

# bin/Hashing_21j    $DSPIN    $HASH_TABLES_STORE_PATH    $FASTWIG_TABLES_PATH    $VERBOSITY

bin/test_sampler   $OMP_NUM_THREADS   $DSPIN   $LENGTH   $SIGMA   $BURNIN   $VERBOSITY   $DRAWS_STORE_PATH   $HASH_TABLES_STORE_PATH