#!/bin/bash

export LD_LIBRARY_PATH="./lib":$LD_LIBRARY_PATH

FASTWIG_TABLES_PATH=./data_folder/fastwig_tables/

HASH_TABLES_STORE_PATH=./data_folder/hashed_21j/

DSPIN=3

VERBOSITY=0

echo Running all tests... 

# bin/test_jsymbols $DATADIR

# bin/Hashing_21j    $DSPIN    $HASH_TABLES_STORE_PATH    $FASTWIG_TABLES_PATH    $VERBOSITY

  bin/test_sampler   