#!/bin/bash

# attach 'valgrind --leak-check=yes' before each bin/... in order to track memory allocations.
# maybe it is also better to compile in debug mode first  

export LD_LIBRARY_PATH="./lib":$LD_LIBRARY_PATH

# this is read as string by main, therefore " " is not necessary
DATADIR=./data_folder  

echo Running all tests... 

bin/test_jsymbols $DATADIR

bin/test_sampler $DATADIR 
