#!/bin/bash

export LD_LIBRARY_PATH="./lib":$LD_LIBRARY_PATH

FASTWIGXJ_TABLES_PATH=./data_folder/fastwigxj_tables

HASH_TABLES_STORE_PATH=./data_folder/21j_hash_tables 

DSPIN=3

now=$(date)
echo
echo "Starting hashing 21j symbols... [ DSPIN = ${DSPIN} ]... (now: $now)"

bin/Hashing_21j    $DSPIN    $HASH_TABLES_STORE_PATH    $FASTWIGXJ_TABLES_PATH 


