#!/bin/bash

export LD_LIBRARY_PATH="./lib":$LD_LIBRARY_PATH

export OMP_NUM_THREADS=12

HASH_TABLES_STORE_PATH=./data_folder/21j_hash_tables/

STORE_PATH=./data_folder/data/

DSPIN=1

LENGTH=1000

SIGMA=0.40

BURNIN=10

VERBOSITY=0

now=$(date)
echo
echo "Starting Metropolis-Hastings algorithm... [ NUM_OF_THREADS = ${OMP_NUM_THREADS} DSPIN = ${DSPIN} LENGTH = ${LENGTH} ]... (now: $now)"

bin/Metropolis_Hastings_parallel_run  $OMP_NUM_THREADS  $DSPIN  $LENGTH  $SIGMA  $BURNIN  $VERBOSITY  $STORE_PATH  $HASH_TABLES_STORE_PATH
            

